### ISSUE TITLE
Missing Side Bar (where participant list is shown) which is mentioned in documentation page

### ISSUE THREAD

**Issue by pawansingh00** [Azure-Samples/communication-services-web-chat-hero#113]
### Missing Side Bar (where participant list is shown) which is mentioned in documentation page

Documentation page seems to have mentioned this -> 

**Side Bar**: This is where participants and setting information are shown when toggled using the controls in the header. The participants side bar contains a list of participants in the chat and a link to invite participants to the chat session. The settings side bar allows you to configure the chat thread title.

**Screenshot from the documentation page**

<img width="707" alt="image" src="https://github.com/Azure-Samples/communication-services-web-chat-hero/assets/27332582/149b8c27-032d-46cf-978e-bd2cc4f5911a">

Documentation Link - https://learn.microsoft.com/en-us/azure/communication-services/samples/chat-hero-sample

I want to add a similar participant list, my main concern is scenarios like this -> If 2 users connect to a chat thread and after sometimes lets say User2 disconnected from internet due to some network issues.

Will the list update on User1 side  and say that now only 1 user (User1) is active??

**Comment by vhuseinova-msft** [comment]
Hello @pawansingh00!
Thank you for your question! 
The participant panel is a beta feature for [@azure/communication-react](https://www.npmjs.com/package/@azure/communication-react?activeTab=readme) and it's not added to [communication-services-web-chat-hero](https://github.com/Azure-Samples/communication-services-web-chat-hero) repository yet.

Please check out more info in the [Docs section](https://azure.github.io/communication-ui-library/iframe.html?viewMode=docs&id=composites-chat-trychatcomposite--try-chat-composite#participant-pane) or in [Preview section](https://azure.github.io/communication-ui-library/?path=/story/composites-chat-trychatcomposite--try-chat-composite) in our storybook.

>I want to add a similar participant list, my main concern is scenarios like this -> If 2 users connect to a chat thread and after sometimes lets say User2 disconnected from internet due to some network issues.
>
>Will the list update on User1 side and say that now only 1 user (User1) is active??

To help us understand how you use Chat UI Library right now, could you please help to clarify the following:
- Do I understand correctly that you use ChatComposite?
- Do you use Chat UI SDK for ACS chat, Teams Interop Chat or some other scenarios?

**Comment by palatter** [comment]
We are closing this issue since we haven’t heard back from you for 10 days. Please feel free to reopen this issue if you have any questions.

**Comment by palatter** [comment]
We are closing this issue since we haven’t heard back from you for 10 days. Please feel free to reopen this issue if you have any questions.
