### ISSUE TITLE
Web-Chat-ACS-Team interop feature 

### ISSUE THREAD

**Issue by RajeshCG** [Azure-Samples/communication-services-web-chat-hero#124]
> Following information related to issue 

I am getting below error while try to enable Teams Federation Configuration to enable Teams Interop  for Azure Communication Resource 

![image](https://github.com/Azure-Samples/communication-services-web-chat-hero/assets/94476064/cce204d7-7d04-482e-befe-2a0da2f7fd03-4345-8c86-6ce56346a78d)

I am referring at [teams-interop-chat-adhoc documentation  ](https://github.com/Azure-Samples/communication-services-web-chat-hero/blob/teams-interop-chat-adhoc/README.md)   to integrate ACS web chat with Teams . Application is giving build errors 

![image](https://github.com/Azure-Samples/communication-services-web-chat-hero/assets/94476064/65f32488-430f-4cd1-a28b-cfe8bc9cd364)

I am referring at [communication-services-web-chat ]( https://github.com/Azure-Samples/communication-services-web-chat-hero/blob/main/README.md)to integrate ACS web chat with ACS so Try to run  communication-services-web-chat-hero from main branch . it is keep on showing as "creating a new chat thread 

![image](https://github.com/Azure-Samples/communication-services-web-chat-hero/assets/94476064/fafbb56c-1179-463a-9672-5211c2abf16a)

 
![image](https://github.com/Azure-Samples/communication-services-web-chat-hero/assets/94476064/b8ab0c92-a154-4f47-b076-2529f972c766)

**Comment by RajeshCG** [comment]
Now I am able to build application but not able to 

it is giving below error , While  enabling Federation feature for Teams tenant ( CAP Dev Test) to  ACS resource So it seems that  ACS preview features are not enabled for  ([Rajesh@capdevtest.onmicrosoft.com](mailto:Rajesh@capdevtest.onmicrosoft.com))
![image] (https://github.com/Azure-Samples/communication-services-web-chat-hero/assets/94476064/4a9110ac-2534-4ef4-8d09-d10b0c4fc218)

it is giving below error, while enabling Federation feature for Teams tenant (Corporate tenant) to ACS resource. So, it seems that user doesn’t have Teams administrator permissions to enable Federation for teams' tenant.

![image](https://github.com/Azure-Samples/communication-services-web-chat-hero/assets/94476064/2c5e7be4-01a3-4510-8b36-528c9cbd3e7e)

**Comment by JoshuaLai** [comment]
Thanks, we are now investigating this and will respond here with our findings.

**Comment by RajeshCG** [comment]
Now I am able enable federation configuration feature to Azure communication service for Teams tenant without any issue. 


While adding Teams user id to the Web chat. Below exception is throwing 

Exception:
Unexpected error occurred while adding a Microsoft Teams user to a thread: Azure.RequestFailedException: **Service request failed.**
**Status: 201 (Created)**

Content:

Headers:
Access-Control-Expose-Headers: REDACTED
MS-CV: REDACTED
Strict-Transport-Security: REDACTED
api-supported-versions: REDACTED
X-Processing-Time: REDACTED
x-ms-client-request-id: 9ff58567-7bdd-4bad-a003-b1e16f94ab03
X-Cache: REDACTED
X-Azure-Ref: REDACTED
Date: Wed, 30 Aug 2023 01:20:50 GMT
Content-Length: 133
Content-Type: application/json; charset=utf-8
   at Azure.Communication.Chat.ChatThreadClient.AddParticipantAsync(ChatParticipant participant, CancellationToken cancellationToken)
   at Chat.ContosoHandshakeController.TryAddTeamsUserToThread(String threadId, ContosoTeamsMemberModel user)

**Comment by RajeshCG** [comment]
Now I am able to chat with Teams user using Teams Adhoc chat feature , Thank you!
