### ISSUE TITLE
Facing port issue in server

### ISSUE THREAD

**Issue by premsagar09** [Azure-Samples/communication-services-web-chat-hero#137]
We develop web applications using the Chat Hero interface, supported by our proprietary backend services. Our deployment strategy involves utilizing Azure App Service, typically on port 8080. However, a sample app provided initially uses port 3000. Despite configuring the deployment to use port 8080, the deployed application seems to default to port 3000, resulting in the following error logs.

ERROR :-" Container app_0_a32d8590 for site app did not start within expected time limit. Elapsed time = 230.9352894 sec
 Container app_0_a32d8590 didn't respond to HTTP pings on port: 8080, failing site start. See container logs for debugging."

**Comment by jpeng-ms** [comment]
Hi @premsagar09 I was wondering if you have resolved this? I see you had another issue for styling, does it mean you are able to sort it out at the end?

**Comment by premsagar09** [comment]
> Hi @premsagar09 I was wondering if you have resolved this? I see you had another issue for styling, does it mean you are able to sort it out at the end?

No, I tried in different ways but it didn't work. deployed directly from visual studio. it was success, now am facing style issues

**Comment by jpeng-ms** [comment]
Thanks for the info @premsagar09 , the hero sample uses two ports actually: 
- 3000 for frontend (/.Chat)
- 8080 for backend (./Server)

So I guess there were some conflicts where client and service were sharing the same port and caused this issue.


I was wondering if you could try the following and let me know if it resolves your issues:

1. https://github.com/Azure-Samples/communication-services-web-chat-hero/blob/dcb8b0a884d419fda0873a7708a4230974f113b4/Chat/common.webpack.config.js#L56 here change the port to 8080
2. then at https://github.com/Azure-Samples/communication-services-web-chat-hero/blob/dcb8b0a884d419fda0873a7708a4230974f113b4/Chat/common.webpack.config.js#L63 and line 63, 67, 71, 75, 79, 83, 87, change the port to 3001
3. then at https://github.com/Azure-Samples/communication-services-web-chat-hero/blob/dcb8b0a884d419fda0873a7708a4230974f113b4/Server/bin/www.ts#L14 change it to `const port = '3001' `

Looking forward to hearing back from you

**Comment by vhuseinova-msft** [comment]
We are closing this issue since we haven’t heard back from you for 10 days. Feel free to reopen this issue if you have any questions.

**Comment by premsagar09** [comment]
Deployed app services from Visual studio. It worked.

Please find below attachment for reference:

https://learn.microsoft.com/en-us/azure/app-service/quickstart-nodejs?tabs=linux&pivots=development-environment-vscode
