### ISSUE TITLE
Styling issue in chat screen 

### ISSUE THREAD

**Issue by premsagar09** [Azure-Samples/communication-services-web-chat-hero#138]
<img width="580" alt="image" src="https://github.com/Azure-Samples/communication-services-web-chat-hero/assets/107998134/a8f6c6d8-6c6c-4d28-a0ed-e3af0b1be420">

After re-loading the page getting above UI issue
How can I fix those?

**Comment by jpeng-ms** [comment]
Hi @premsagar09 we have updated the repo with some changes, would you mind trying again and let us know if you still face this issue?

**Comment by premsagar09** [comment]
Sure, thank you

let me try

**Comment by premsagar09** [comment]
> Hi @premsagar09 we have updated the repo with some changes, would you mind trying again and let us know if you still face this issue?

Sure, thank you

let me try

**Comment by vhuseinova-msft** [comment]
We are closing this issue since we haven’t heard back from you for 10 days. Feel free to reopen this issue if you have any questions.
