### ISSUE TITLE
Stuck "Initializing chat client..."

### ISSUE THREAD

**Issue by M365-DenzilFernandes** [Azure-Samples/communication-services-web-chat-hero#17]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Straight Deploy to Azure from this Repo

### Any log messages given by the failure
> None

### Expected/desired behavior
> Chat would load after selecting avatar and entering username

### OS and Version?
> Windows 10 + Chrome

### Versions
>

### Mention any other details that might be useful
Deployment successful, but when launching the site after entering the details I cannot see the interface for chat

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by prprabhu-ms** [comment]
Thanks for filing this issue.
I just tried a deploy from main and succeeded. I was also able to join new chat thread from the new deployment.

If you haven't deleted the deployment, can you see if there was some (unexpected) latency in setup on the backend (i.e., try again once). Also, if you have any other broswer can you give it a spin? (firefox / edge).

**Comment by M365-DenzilFernandes** [comment]
Thanks. I will attempt using other browsers. So far both Edge and Chrome in either Incognito/Private or non appears to be the same. No deployment errors after checking. Will test other browsers and try mobile next

**Comment by alkwa-msft** [comment]
Had Denzil try it out again and it seemed to be working fine so I am closing this issue.
