### ISSUE TITLE
Deployment failed with Node 16 LTS

### ISSUE THREAD

**Issue by aarthiem** [Azure-Samples/communication-services-web-chat-hero#47]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Deploy the app using App service extension and select runtime as Node 16 LTS

### Any log messages given by the failure
>6:48:01 PM appservice41: Using Node version:
6:48:01 PM appservice41: v16.14.2
6:48:01 PM appservice41: Using Npm version:
6:48:01 PM appservice41: 8.5.0
6:48:01 PM appservice41: Running 'npm install --unsafe-perm'...
6:48:02 PM appservice41: npm ERR! Tracker "idealTree" already exists
6:48:02 PM appservice41: npm ERR! A complete log of this run can be found in:
6:48:02 PM appservice41: npm ERR!     /home/.npm/_logs/2022-04-18T22_48_02_003Z-debug-0.log

### Expected/desired behavior
> Successful deployment

### OS and Version?
> Linux

### Versions
>Node 16

### Mention any other details that might be useful
Deployment works with Node 14. So, need clarity why is Node 16 not supported.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by anjulgarg** [comment]
Hello @aarthiem 
We are looking into it and will get back to you soon.

**Comment by anjulgarg** [comment]
Hi @aarthiem 
We were able to deploy the app successfully to Azure App Service using the `Deploy to Azure` button  and following the steps.
![image](https://user-images.githubusercontent.com/9782747/164119819-9475b1bc-0b91-42ff-b055-5f345ae8580a.png)

I can't comment on why it's failing when you are trying to use the vscode plugin.
Maybe try creating a video showing what you are doing step by step so that we have more clarity on what could be wrong?

**Comment by alkwa-msft** [comment]
Under the hood. Azure App Service instances seem to use docker images. With Node 15+ It seems there is an issue with where commands are invoked in docker containers.  We are going to just suggest at this time customers use Node 14 in their dev environment and when they are deploying to Azure at this time.

https://stackoverflow.com/questions/57534295/npm-err-tracker-idealtree-already-exists-while-creating-the-docker-image-for

**Comment by alkwa-msft** [comment]
PR to update docs. 
https://github.com/Azure-Samples/communication-services-web-chat-hero/pull/50

Thanks for logging this issue @aarthiem

**Comment by aarthiem** [comment]
Thanks for addressing the issue @alkwa-msft
