### ISSUE TITLE
Send attachments and push notifications

### ISSUE THREAD

**Issue by nithishk** [Azure-Samples/communication-services-web-chat-hero#76]
Is it possible to get push notifications and send attachments ?

**Comment by carocao-msft** [comment]
Hi, 
We have not invested push notifications yet but it is something we can definitely add to the backlog.

For sending attachments we do support that with https://github.com/Azure-Samples/communication-services-javascript-quickstarts/tree/main/ui-library-filesharing-chat-composite, however today we don't have plans about bringing file sharing into the chat hero sample but it is something we can add to the backlog as well.

Let me know if that answers your question
Thanks!

**Comment by mgamis-msft** [comment]
Closing this issue due to > 10 days with no response
