### ISSUE TITLE
Instructions on how to change the AdminUserId in Server/appsettings.json

### ISSUE THREAD

**Issue by fpereiramapfrepr** [Azure-Samples/communication-services-web-chat-hero#93]
Hi, I'm trying to run the example without any success.

I believed that the AdminUserId in Server/appsettings.json should be change and there is no instructions on how to change it on the documentation.

https://learn.microsoft.com/en-us/azure/communication-services/samples/chat-hero-sample

After running "npm run start" the Client and Server apps get running on http://localhost:3000/ and   http://localhost:8080

But once I clicked the button on the client app "Start Chat" and error appears in the terminal.

```
 FetchError: request to https://acs-demo-xxxxx.communication.azure.com/identities/**REPLACE_WITH_ADMIN_USER_ID**/:issueAccessToken?api-version=2021-03-07 failed, reason: read ECONNRESET
[0]     at ClientRequest.<anonymous> (C:\Proyectos\ACS\communication-services-web-chat-hero\Server\node_modules\node-fetch\lib\index.js:1491:11)
[0]     at ClientRequest.emit (node:events:513:28)
[0]     at TLSSocket.socketErrorListener (node:_http_client:496:9)
[0]     at TLSSocket.emit (node:events:513:28)
```

**Comment by alkwa-msft** [comment]
![image](https://user-images.githubusercontent.com/79329532/212414239-d3dc3ac4-2565-45d8-8aa6-9585d1c5bb6f.png)

It exists in the instructions in the Chat Hero Sample. Is that sufficient or do you have any suggestions on how we can be more helpful?
https://github.com/Azure-Samples/communication-services-web-chat-hero/blob/main/README.md

**Comment by alkwa-msft** [comment]
I think for the readme in the chat hero sample we wrote samples as part of the path and that is a copy and paste error so I can adjust the string to just say /Server/appsettings.json

**Comment by alkwa-msft** [comment]
Hopefully this issue is now resolved. If it is we can close it. If there is no response over the next few days I will close this issue.

**Comment by fpereiramapfrepr** [comment]
Thanks! It is working now.
