### ISSUE TITLE
Instructions on how to deploy to local IIS

### ISSUE THREAD

**Issue by fpereiramapfrepr** [Azure-Samples/communication-services-web-chat-hero#95]
Hi, 

Are there any instructions on how to deploy the Client and Server applications to an on-premise IIS? 

I have worked before with ASP.NET Core MVC , never with React. 

Wondering also if I can use the React Composite UI Library on an MVC view? Any tutorial on this?

Awesome work!

Thanks,

**Comment by alkwa-msft** [comment]
https://learn.microsoft.com/en-us/visualstudio/javascript/tutorial-asp-net-core-with-react?view=vs-2022

ASP.net is a web application framework designed to build server applications with web front-ends. ReactJS is front-end tool to help create componentized front-end experiences. This documentation page I have linked shows how to serve up ReactJS content from an asp.net application. To use the web UI Library built in React you will need to import in the library and use the component on the client code served to the end user.

There is no tutorial at this time but this is something we could look into building and sharing if there is interest.

**Comment by fpereiramapfrepr** [comment]
Thanks! I'm sure a lot of people would be interested on see how they can leverage their prior knowledge of ASP.Net with ACS.

Also, is there any tutorial on how to deploy de VSCode Client and Server app to IIS?

Thanks,
