### ISSUE TITLE
Cant join two people in the Chat Room

### ISSUE THREAD

**Issue by fpereiramapfrepr** [Azure-Samples/communication-services-web-chat-hero#96]
I'm able to run the chat in http://localhost:3000/ , but Im unable to chat with someone.  My understanding was that if I opened two browser I could chat between the different person in the chat. It seems the app is creating a different "chat  room" for every person \ browser?

![ChatImages](https://user-images.githubusercontent.com/100782509/212681807-663a2a66-2d5e-454b-b153-0c1ea89dc942.png)

**Comment by fpereiramapfrepr** [comment]
Ok. I copied the URL with the threadId in another browser and was able to chat as two different persons.

**Comment by edwardlee-msft** [comment]
Hi @fpereiramapfrepr ,

That is correct! If you would like to join the same chat room with two different users they must be use the same chat thread. This can be accomplished by copying the same URL with the same threadid in another browser like you have mentioned. 

Thanks for reaching out and notifying us that you had resolved your own issue! :).
