### ISSUE TITLE
Where is the chat history stored?

### ISSUE THREAD

**Issue by fpereiramapfrepr** [Azure-Samples/communication-services-web-chat-hero#97]
Is it possible to get the chat history? Is there an Azure API to see the history of the chat?

**Comment by jimchou-dev** [comment]
Hi @fpereiramapfrepr, thanks for filling a question. Yes you can get the chat history for a chat thread using [ChatSDK](https://learn.microsoft.com/en-us/azure/communication-services/concepts/chat/sdk-features) for the language of your choosing.

For Javascript ChatSDK, please refer to the [example](https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/chat/get-started?tabs=windows&pivots=programming-language-javascript#receive-chat-messages-from-a-chat-thread) for `chatThreadClient.listMessages()`.

Make sure you are using the ChatClient/ChatThreadClient as a user that is part of a `chatThread`. For more information refer to [concepts](https://learn.microsoft.com/en-us/azure/communication-services/concepts/chat/concepts)
