### ISSUE TITLE
Can I chat with a "Teams user" identity?

### ISSUE THREAD

**Issue by fpereiramapfrepr** [Azure-Samples/communication-services-web-chat-hero#98]
Is it possible to chat to a specific users of  the Azure tenant and that person see the chat on its MS Teams chat application? 
Example a customer chatting using the "Chat Hero app" and the employee responding with using MS Teams to the chat?

**Comment by jimchou-dev** [comment]
Hi @fpereiramapfrepr, thanks for filing the issue. Currently the "Chat Hero app" is not able to directly chat with a MS Teams user identity as a stand alone conversation. But thank you for showing interest in this capability, there is a feature backlog for this and I will indicate there is demand for this from the customer, hopefully coming soon in the future.

For the Teams Interoperability scenario however, ChatSDK can be used in conjunction with the CallingSDK. When an `ACS identity user` is admitted into a MS Teams meeting (with other Teams identity user), the ACS user then have access to the associated meeting `chatThread`, and can interact with the `chatThread` through the ChatSDK.

Here are some additional resource to see it in action but requires more setup:
- Communication UI Library [CallWithChat sample](https://github.com/Azure/communication-ui-library/tree/main/samples/CallWithChat)
- [Teams Interoperability](https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/chat/meeting-interop?pivots=platform-web) with ChatSDK and CallingSDK
